export { default as Product } from './Products/ProductAdditionForm';
export { default as Products } from './Products/ProductsTable';
export { default as Orders } from './Orders/OrdersTable';
export { default as MainPage } from './MainPage';
export { default as CoreLayout } from './CoreLayout';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as User } from './Users/UserProfile';
export { default as Users } from './Users/UsersTable';
